use crate::cli::{Cli, SpecFormat};
/// CLI specification generation
///
/// Generates command specifications in various formats (markdown, JSON)
use anyhow::Result;
use clap::{Arg, Command, CommandFactory};
use serde::Serialize;
use std::io;

#[derive(Serialize)]
pub struct SpecEntry {
    pub path: Vec<String>,
    pub about: Option<String>,
    pub arguments: Vec<String>,
}

/// Generate and output CLI specification
pub fn handle_spec(format: SpecFormat) -> Result<()> {
    let root = Cli::command();
    let mut entries = collect_spec_entries(&root);
    entries.sort_by(|a, b| a.path.cmp(&b.path));

    match format {
        SpecFormat::Markdown => print_spec_markdown(&entries),
        SpecFormat::Json => {
            serde_json::to_writer_pretty(io::stdout(), &entries)?;
            println!();
        }
    }

    Ok(())
}

fn collect_spec_entries(command: &Command) -> Vec<SpecEntry> {
    let mut entries = Vec::new();
    for sub in command.get_subcommands() {
        let mut path = vec!["nabi".to_string(), sub.get_name().to_string()];
        collect_spec_recursive(sub, &mut path, &mut entries);
    }
    entries
}

fn collect_spec_recursive(command: &Command, path: &mut Vec<String>, entries: &mut Vec<SpecEntry>) {
    let arguments = command
        .get_arguments()
        .filter(|arg| !arg.is_hide_set())
        .map(summarize_argument)
        .collect();

    entries.push(SpecEntry {
        path: path.clone(),
        about: command.get_about().map(|s| s.to_string()),
        arguments,
    });

    for sub in command.get_subcommands() {
        path.push(sub.get_name().to_string());
        collect_spec_recursive(sub, path, entries);
        path.pop();
    }
}

fn summarize_argument(arg: &Arg) -> String {
    let mut parts = Vec::new();

    if let Some(long) = arg.get_long() {
        parts.push(format!("--{}", long));
    }

    if let Some(short) = arg.get_short() {
        parts.push(format!("-{}", short));
    }

    if parts.is_empty() {
        let id = arg.get_id().as_str().to_string();
        // Check if this is a positional argument based on id format
        if !id.starts_with("--") {
            parts.push(format!("<{}>", id));
        } else {
            parts.push(format!("--{}", id));
        }
    }

    parts.join(", ")
}

fn print_spec_markdown(entries: &[SpecEntry]) {
    println!("# nabi CLI Command Specification\n");
    println!("Generated by `nabi self spec --format markdown`.\n");

    for entry in entries {
        let command = entry.path.join(" ");
        println!("### `{}`", command);

        if let Some(about) = &entry.about {
            println!("{}.", about.trim());
        }

        if !entry.arguments.is_empty() {
            println!("\n**Arguments:**");
            for arg in &entry.arguments {
                println!("- `{}`", arg);
            }
        }

        println!();
    }
}
